# Generated by Django 6.1 on 2026-09-02 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('products', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField(db_index=True, default=0.0)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High (>=85%)'), ('MEDIUM', 'Medium (70-84%)'), ('LOW', 'Low (<70%)')], db_index=True, default='LOW', max_length=20)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERRIDDEN', 'Overridden')], db_index=True, default='APPROVED', max_length=20)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('text_evidence', models.TextField(blank=True, default='')),
                ('image_evidence', models.TextField(blank=True, default='')),
                ('signals_breakdown', models.JSONField(blank=True, default=dict)),
                ('model_version', models.CharField(default='v1.0', max_length=100)),
                ('classifier_version', models.CharField(default='hybrid-bm25-vector-rerank', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classified_products', to='taxonomy.taxonomycategory')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_result', to='products.product')),
                ('taxonomy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_results', to='taxonomy.taxonomyversion')),
            ],
            options={
                'db_table': 'classification_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationAlternative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(default=1)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True, default='')),
                ('supporting_evidence', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternative_results', to='taxonomy.taxonomycategory')),
                ('classification_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='classification.classificationresult')),
            ],
            options={
                'db_table': 'classification_alternatives',
                'ordering': ['classification_result', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(default='hybrid-retrieval-reranker-v1', max_length=150)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('successful_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_runs', to='catalogs.catalog')),
            ],
            options={
                'db_table': 'classification_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_value', models.CharField(max_length=500)),
                ('normalized_value', models.CharField(blank=True, default='', max_length=500)),
                ('is_valid_taxonomy_value', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('STRUCTURED', 'Structured Field'), ('MULTIMODAL', 'Multimodal')], default='TEXT', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracted_values', to='taxonomy.taxonomyattribute')),
                ('classification_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_attributes', to='classification.classificationresult')),
            ],
            options={
                'db_table': 'extracted_attributes',
                'ordering': ['attribute__name'],
            },
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['confidence_level'], name='classificat_confide_e9810b_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['status'], name='classificat_status_1f9a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='classificationresult',
            index=models.Index(fields=['confidence_score'], name='classificat_confide_da0197_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classificationalternative',
            unique_together={('classification_result', 'rank')},
        ),
    ]
