# Generated by Django 6.1 on 2026-09-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationresult',
            name='ai_model',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='ai_provider',
            field=models.CharField(default='hybrid_heuristic', max_length=50),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='ai_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='attribute_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='bm25_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='completeness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='evidence_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='hierarchical_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='image_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='image_status',
            field=models.CharField(default='NO_IMAGE', max_length=50),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='retrieval_method',
            field=models.CharField(default='bm25_semantic_rrf', max_length=100),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='rrf_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='semantic_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='was_ai_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='confidence_level',
            field=models.CharField(choices=[('HIGH', 'High (>=85%)'), ('MEDIUM', 'Medium (60-84%)'), ('LOW', 'Low (<60%)')], db_index=True, default='LOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERRIDDEN', 'Overridden')], db_index=True, default='PENDING_REVIEW', max_length=20),
        ),
    ]
