# Generated by Django 6.1 on 2026-09-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_classificationresult_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationresult',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
