# Generated by Django 6.1 on 2026-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_classificationresult_review_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationresult',
            name='ai_decision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='ai_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='ai_processing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='ai_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
