# Generated by Django 6.1 on 2026-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_classificationresult_ai_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationresult',
            name='ai_called',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classificationresult',
            name='ai_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='ai_provider',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AlterField(
            model_name='classificationresult',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERRIDDEN', 'Overridden'), ('RULE_VALIDATED', 'Rule Validated'), ('LOCAL_LLM_APPROVED', 'Local LLM Approved')], db_index=True, default='PENDING_REVIEW', max_length=20),
        ),
    ]
