# Generated by Django 6.1 on 2026-09-02 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('CLASSIFICATION', 'Full Classification'), ('RETRY_FAILED', 'Retry Failed Products'), ('IMAGE_DOWNLOAD', 'Image Fetch & Cache')], default='CLASSIFICATION', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('successful_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('current_step', models.CharField(default='Initialized', max_length=255)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='catalogs.catalog')),
            ],
            options={
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
