# Generated by Django 6.1 on 2026-09-02 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='classified_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='done_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='failed_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='needs_review_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='pending_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='running_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='total_chunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partially Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='JobChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('start_index', models.IntegerField(default=0)),
                ('end_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='jobs.processingjob')),
            ],
            options={
                'db_table': 'job_chunks',
                'ordering': ['chunk_index'],
            },
        ),
    ]
