import React, { useState } from 'react';
import { Settings, Sliders, Cpu, Save, ShieldCheck, Check } from 'lucide-react';

export const SettingsPage: React.FC = () => {
  const [provider, setProvider] = useState('hybrid_heuristic');
  const [batchSize, setBatchSize] = useState(50);
  const [maxRetries, setMaxRetries] = useState(3);
  const [weights, setWeights] = useState({
    semantic: 0.25,
    lexical: 0.15,
    hierarchy: 0.15,
    llm: 0.20,
    attribute: 0.10,
    image: 0.10,
    completeness: 0.05,
  });
  const [isSaved, setIsSaved] = useState(false);

  const handleSave = () => {
    setIsSaved(true);
    setTimeout(() => setIsSaved(false), 2500);
  };

  const totalWeight = Object.values(weights).reduce((a, b) => a + b, 0);

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-in fade-in duration-200">
      <div>
        <div className="flex items-center space-x-2">
          <Settings className="w-5 h-5 text-indigo-400" />
          <h1 className="text-xl font-bold text-white">Pipeline & Confidence Settings</h1>
        </div>
        <p className="text-xs text-slate-400">
          Configure AI providers, multi-signal confidence weights, and background batch execution parameters
        </p>
      </div>

      {/* AI Provider Config */}
      <div className="glass-panel rounded-3xl p-6 border border-slate-800 space-y-4">
        <div className="flex items-center space-x-2">
          <Cpu className="w-4 h-4 text-indigo-400" />
          <h2 className="text-sm font-bold text-white">AI Classification & Reranker Provider</h2>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
          <button
            onClick={() => setProvider('hybrid_heuristic')}
            className={`p-4 rounded-2xl border text-left transition ${
              provider === 'hybrid_heuristic'
                ? 'bg-indigo-600/20 border-indigo-500 text-white'
                : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:bg-slate-900'
            }`}
          >
            <div className="font-bold text-white">Hybrid Heuristic & TF-IDF</div>
            <div className="text-[11px] text-slate-400 mt-1">
              Zero-API-key local semantic reranker. High throughput & offline ready.
            </div>
          </button>

          <button
            onClick={() => setProvider('gemini')}
            className={`p-4 rounded-2xl border text-left transition ${
              provider === 'gemini'
                ? 'bg-indigo-600/20 border-indigo-500 text-white'
                : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:bg-slate-900'
            }`}
          >
            <div className="font-bold text-white">Google Gemini 1.5 Flash</div>
            <div className="text-[11px] text-slate-400 mt-1">
              Multimodal LLM for visual + textual deep reranking.
            </div>
          </button>

          <button
            onClick={() => setProvider('openai')}
            className={`p-4 rounded-2xl border text-left transition ${
              provider === 'openai'
                ? 'bg-indigo-600/20 border-indigo-500 text-white'
                : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:bg-slate-900'
            }`}
          >
            <div className="font-bold text-white">OpenAI GPT-4o Mini</div>
            <div className="text-[11px] text-slate-400 mt-1">
              Multimodal provider with structured JSON tool output.
            </div>
          </button>
        </div>
      </div>

      {/* Multi-Signal Confidence Weights */}
      <div className="glass-panel rounded-3xl p-6 border border-slate-800 space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Sliders className="w-4 h-4 text-indigo-400" />
            <h2 className="text-sm font-bold text-white">Multi-Signal Confidence Scoring Weights</h2>
          </div>
          <span className="text-xs font-mono text-indigo-400 bg-indigo-500/10 px-2.5 py-1 rounded-full">
            Total Sum: {(totalWeight * 100).toFixed(0)}%
          </span>
        </div>

        <div className="space-y-4 text-xs">
          {[
            { key: 'semantic', label: 'Semantic Similarity (Embeddings)', desc: 'Dense vector cosine distance to category definitions' },
            { key: 'llm', label: 'AI Reranker Score', desc: 'Confidence generated by reranking model' },
            { key: 'lexical', label: 'Lexical Match (BM25)', desc: 'Token overlap with category paths and keywords' },
            { key: 'hierarchy', label: 'Hierarchy Consistency', desc: 'Depth & parent vertical validity' },
            { key: 'attribute', label: 'Attribute Consistency', desc: 'Valid taxonomy attribute values match' },
            { key: 'image', label: 'Image Visual Evidence', desc: 'Valid downloaded product image support' },
            { key: 'completeness', label: 'Data Completeness', desc: 'Presence of title, description, brand, and specs' },
          ].map((item) => (
            <div key={item.key} className="space-y-1">
              <div className="flex items-center justify-between text-slate-300">
                <div>
                  <span className="font-semibold text-white">{item.label}</span>
                  <span className="text-[11px] text-slate-500 ml-2">({item.desc})</span>
                </div>
                <span className="font-mono font-bold text-indigo-400">
                  {((weights as any)[item.key] * 100).toFixed(0)}%
                </span>
              </div>
              <input
                type="range"
                min="0"
                max="0.5"
                step="0.01"
                value={(weights as any)[item.key]}
                onChange={(e) =>
                  setWeights({ ...weights, [item.key]: parseFloat(e.target.value) })
                }
                className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-indigo-500"
              />
            </div>
          ))}
        </div>
      </div>

      {/* Batch Execution Parameters */}
      <div className="glass-panel rounded-3xl p-6 border border-slate-800 space-y-4">
        <h2 className="text-sm font-bold text-white">Batch & Scalability Parameters</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs">
          <div className="space-y-1">
            <label className="text-slate-400 font-medium">Batch Chunk Size</label>
            <input
              type="number"
              value={batchSize}
              onChange={(e) => setBatchSize(parseInt(e.target.value) || 50)}
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-indigo-500"
            />
          </div>
          <div className="space-y-1">
            <label className="text-slate-400 font-medium">Max Retries on Failure</label>
            <input
              type="number"
              value={maxRetries}
              onChange={(e) => setMaxRetries(parseInt(e.target.value) || 3)}
              className="w-full bg-slate-950 border border-slate-700 rounded-xl px-3 py-2 text-white focus:outline-none focus:border-indigo-500"
            />
          </div>
        </div>
      </div>

      <div className="flex justify-end">
        <button
          onClick={handleSave}
          className="px-6 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold rounded-xl shadow-lg shadow-indigo-600/30 transition flex items-center space-x-2"
        >
          {isSaved ? <Check className="w-4 h-4" /> : <Save className="w-4 h-4" />}
          <span>{isSaved ? 'Settings Saved!' : 'Save Configuration'}</span>
        </button>
      </div>
    </div>
  );
};
