# Generated by Django 6.1 on 2026-09-02 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('OVERRIDE', 'Override Category'), ('REJECT', 'Reject')], max_length=20)),
                ('reviewer', models.CharField(default='system_admin', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='classification.classificationresult')),
                ('new_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_to', to='taxonomy.taxonomycategory')),
                ('old_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_from', to='taxonomy.taxonomycategory')),
            ],
            options={
                'db_table': 'review_decisions',
                'ordering': ['-created_at'],
            },
        ),
    ]
