# Generated by Django 6.1 on 2026-09-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(default='Shopify Standard Product Taxonomy', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taxonomy_versions',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=150)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('full_path', models.CharField(db_index=True, max_length=1000)),
                ('level', models.IntegerField(default=0)),
                ('is_leaf', models.BooleanField(db_index=True, default=True)),
                ('is_root', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('ancestor_ids', models.JSONField(blank=True, default=list)),
                ('children_ids', models.JSONField(blank=True, default=list)),
                ('attribute_ids', models.JSONField(blank=True, default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_categories', to='taxonomy.taxonomycategory')),
                ('taxonomy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='taxonomy.taxonomyversion')),
            ],
            options={
                'db_table': 'taxonomy_categories',
                'ordering': ['full_path'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=150)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('handle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('data_type', models.CharField(default='choice', max_length=50)),
                ('taxonomy_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='taxonomy.taxonomyversion')),
            ],
            options={
                'db_table': 'taxonomy_attributes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxonomyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=150)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonomy.taxonomyattribute')),
            ],
            options={
                'db_table': 'taxonomy_attribute_values',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['attribute', 'normalized_name'], name='taxonomy_at_attribu_498f46_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_categories', to='taxonomy.taxonomyattribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='taxonomy.taxonomycategory')),
            ],
            options={
                'db_table': 'category_attributes',
                'unique_together': {('category', 'attribute')},
            },
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['taxonomy_version', 'is_leaf'], name='taxonomy_ca_taxonom_a06f13_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['name'], name='taxonomy_ca_name_9c07a7_idx'),
        ),
        migrations.AddIndex(
            model_name='taxonomycategory',
            index=models.Index(fields=['full_path'], name='taxonomy_ca_full_pa_f54a2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxonomycategory',
            unique_together={('taxonomy_version', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='taxonomyattribute',
            index=models.Index(fields=['name'], name='taxonomy_at_name_240bc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taxonomyattribute',
            unique_together={('taxonomy_version', 'external_id')},
        ),
    ]
