# Generated by Django 6.1 on 2026-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoryattribute',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxonomyattribute',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxonomyattributevalue',
            name='handle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='taxonomyattributevalue',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxonomycategory',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='asset_checksums',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='release_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='release_status',
            field=models.CharField(default='STABLE', max_length=50),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='release_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='source_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxonomyversion',
            name='status',
            field=models.CharField(choices=[('IMPORTING', 'Importing'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed')], db_index=True, default='IMPORTING', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxonomyversion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
