# Generated by Django 6.1 on 2026-09-02 08:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_number', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('model_number', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('bullets', models.TextField(blank=True, default='')),
                ('brand', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('product_type', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('materials', models.CharField(blank=True, default='', max_length=500)),
                ('color', models.CharField(blank=True, default='', max_length=200)),
                ('color_collection', models.CharField(blank=True, default='', max_length=200)),
                ('dimensions', models.CharField(blank=True, default='', max_length=500)),
                ('set_includes', models.TextField(blank=True, default='')),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('map_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=100)),
                ('shipping_method', models.CharField(blank=True, default='', max_length=150)),
                ('product_url', models.URLField(blank=True, default='', max_length=1000)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('MANUAL_REVIEW', 'Manual Review')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogs.catalog')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000)),
                ('position', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADED', 'Downloaded'), ('FAILED', 'Failed'), ('INVALID', 'Invalid')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('image_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['product', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog', 'processing_status'], name='products_catalog_cb0d60_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_number'], name='products_product_77e2e3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_brand_b2547a_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'position'], name='product_ima_product_8c4733_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['image_hash'], name='product_ima_image_h_e621a9_idx'),
        ),
    ]
