# Generated by Django 6.1 on 2026-09-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_skipped_reclassification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='skip_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='source_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['source_fingerprint'], name='products_source__000c44_idx'),
        ),
    ]
