# Generated by Django 6.1 on 2026-09-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_skipped_reclassification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CLASSIFIED', 'Classified'), ('AUTO_APPROVED', 'Auto Approved'), ('REQUIRES_REVIEW', 'Requires Review'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
