# Generated by Django 6.1 on 2026-09-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decision_status',
            field=models.CharField(choices=[('NOT_REVIEWED', 'Not Reviewed'), ('AUTO_CLASSIFIED', 'Auto Classified'), ('ADMIN_APPROVED', 'Admin Approved'), ('ADMIN_DECLINED', 'Admin Declined'), ('REQUIRES_REVIEW', 'Requires Review')], db_index=True, default='NOT_REVIEWED', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='decline_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CLASSIFIED', 'Classified'), ('AUTO_APPROVED', 'Auto Approved'), ('REQUIRES_REVIEW', 'Requires Review'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed'), ('MANUAL_REVIEW', 'Manual Review')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
